// lib/config/env.public.ts

export const publicEnv = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  NEXT_PUBLIC_ROOT_DOMAIN: process.env.NEXT_PUBLIC_ROOT_DOMAIN!,
  NEXT_PUBLIC_APP_SUBDOMAIN: process.env.NEXT_PUBLIC_APP_SUBDOMAIN!,
  NEXT_PUBLIC_ADMIN_SUBDOMAIN: process.env.NEXT_PUBLIC_ADMIN_SUBDOMAIN!,
  NEXT_PUBLIC_UNSPLASH_ACCESS_KEY: process.env.NEXT_PUBLIC_UNSPLASH_ACCESS_KEY!,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!,
};
